# Generated by Django 5.1.7 on 2025-03-13 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('interests', models.TextField(blank=True)),
                ('course_major', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('drinking_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('sleep_habits', models.CharField(choices=[('early_riser', 'Early Riser'), ('night_owl', 'Night Owl'), ('average', 'Average')], default='average', max_length=20)),
                ('study_habits', models.CharField(choices=[('in_room', 'In Room'), ('library', 'Library'), ('other_places', 'Other Places')], default='library', max_length=20)),
                ('guests_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('sometimes', 'Sometimes'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('cleanliness_level', models.IntegerField(default=3, help_text='Scale of 1-5, 5 being the cleanest')),
                ('max_rent_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_move_in_date', models.DateField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to='user_profiles.userprofile')),
            ],
        ),
    ]
